algoritmo "semnome"
// Função :
// Autor : Daniel da Silva
// Data : 09/07/2022
// Seção de Declarações 
var
numero:caracter
convertido:inteiro
comprimento:inteiro

inicio

escreval("Digite um número: ")
leia(numero)
convertido <- asc(numero)
comprimento <- compr(numero)

escreval("Numero digitado é ",convertido)
escreval("Comprimento Número digitado é: ",comprimento)

fimalgoritmo
