algoritmo "ex1"
// Função : Faça um algoritmo que escreva na tela os números de um número inicial a um número final.
//Os números inicial e final devem ser informados pelo usuário.
var
i,numero,numero2:inteiro

inicio
escreval("Digite seu 1° Numero: ")
leia(numero)
escreval("Digite seu 2° Numero: ")
leia(numero2)

para i <- numero ate numero2 faca
escreval(i)

fimpara






fimalgoritmo
