algoritmo "semnome"
// Faça um programa que receba 5 numeros
// digitados pelo usuários e ao final mostra a soma deles.
var
contador,numero,soma,qtde:inteiro
media:real
inicio
para contador de 1 ate 550 faca
 se (contador mod 2 = 0)entao
 soma <- soma + contador
 qtde <- qtde + 1
fimse
fimpara
escreval("A soma é: ",soma)
escreval("Achei ",qtde," de pares")
media <- soma/qtde
escreval("A média é: ",media)
fimalgoritmo
